// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Constructor.Core.Templates
{
    using System.Linq;
    using Constructor.Core.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EntityConfiguration : EntityConfigurationBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing Microsoft.EntityFrameworkCore;\r\nusing Microsoft.EntityFrameworkCore.Metadata.Builders;\r\n\r\nnamespace ");
            
            #line 11 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 13 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.Name));
            
            #line default
            #line hidden
            this.Write("Configuration : IEntityTypeConfiguration<");
            
            #line 13 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public void Configure(EntityTypeBuilder<");
            
            #line 15 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.Name));
            
            #line default
            #line hidden
            this.Write("> builder)\r\n        {\r\n            ");
            
            #line 17 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    if (EntityOptions.IsTable)
    {

            
            #line default
            #line hidden
            this.Write("            builder.ToTable(\"");
            
            #line 21 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.TableOrViewName));
            
            #line default
            #line hidden
            this.Write("\",\"");
            
            #line 21 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.SchemaName));
            
            #line default
            #line hidden
            this.Write("\");\r\n            ");
            
            #line 22 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("            builder.ToView(\"");
            
            #line 27 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.TableOrViewName));
            
            #line default
            #line hidden
            this.Write("\",\"");
            
            #line 27 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.SchemaName));
            
            #line default
            #line hidden
            this.Write("\");\r\n            ");
            
            #line 28 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }

            
            #line default
            #line hidden
            this.Write("             ");
            
            #line 31 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    if (EntityOptions.Properties.Any(x => x.IsPrimaryKey))
    {

            
            #line default
            #line hidden
            this.Write("            builder.HasKey(x => x.");
            
            #line 35 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.Properties.FirstOrDefault(x => x.IsPrimaryKey)!.Name));
            
            #line default
            #line hidden
            this.Write(").HasName(\"");
            
            #line 36 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityOptions.Properties.FirstOrDefault(x => x.IsPrimaryKey)!.ColumnName));
            
            #line default
            #line hidden
            this.Write("\");\r\n            ");
            
            #line 38 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 41 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    var primaryKeyProperty = EntityOptions.Properties.FirstOrDefault(x => x.IsPrimaryKey)!;
    EntityOptions.Properties.ToList().Remove(primaryKeyProperty);

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 45 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    foreach (var property in EntityOptions.Properties)
    {

            
            #line default
            #line hidden
            this.Write("            builder.Property(x => x.");
            
            #line 49 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n                    .HasColumnName(\"");
            
            #line 50 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ColumnName));
            
            #line default
            #line hidden
            this.Write("\")\r\n                    .HasPrecision(");
            
            #line 51 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Precision));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 51 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Scale));
            
            #line default
            #line hidden
            this.Write(")\r\n                    ");
            
            #line 52 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        if (property.IsRequired)
        {

            
            #line default
            #line hidden
            this.Write(".IsRequired()");
            
            #line 55 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        }

            
            #line default
            #line hidden
            
            #line 57 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        if (property.MaxLength > 0)
        {

            
            #line default
            #line hidden
            this.Write(".HasMaxLength(");
            
            #line 60 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.MaxLength));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 60 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        }

            
            #line default
            #line hidden
            
            #line 62 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        if (property.IsUnicode)
        {

            
            #line default
            #line hidden
            this.Write(".IsUnicode()");
            
            #line 65 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        }

            
            #line default
            #line hidden
            this.Write(";\r\n            ");
            
            #line 68 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 71 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    foreach (var relationship in EntityOptions.OneToOneRelationships)
    {

            
            #line default
            #line hidden
            this.Write("            builder.HasOne(x => x.");
            
            #line 75 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.RightEntity));
            
            #line default
            #line hidden
            this.Write(")\r\n                    .WithOne(x => x.");
            
            #line 76 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.LeftEntity));
            
            #line default
            #line hidden
            this.Write(")\r\n                    .HasForeignKey<");
            
            #line 77 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.LeftEntity));
            
            #line default
            #line hidden
            this.Write(">(x => x.");
            
            #line 77 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.FkProperty));
            
            #line default
            #line hidden
            this.Write(")\r\n                    ");
            
            #line 78 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        if (relationship.IsRequired)
        {

            
            #line default
            #line hidden
            this.Write(".IsRequired()");
            
            #line 81 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        }

            
            #line default
            #line hidden
            this.Write("                    .OnDelete(DeleteBehavior.");
            
            #line 84 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.DeleteBehavior));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 85 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 88 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    foreach (var relationship in EntityOptions.OneToManyRelationships)
    {

            
            #line default
            #line hidden
            this.Write("            builder.HasMany(x => x.");
            
            #line 92 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.RightEntity));
            
            #line default
            #line hidden
            this.Write(")\r\n                    .WithOne(x => x.");
            
            #line 93 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.LeftEntity));
            
            #line default
            #line hidden
            this.Write(")\r\n                    .HasForeignKey(x => x.");
            
            #line 94 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.FkProperty));
            
            #line default
            #line hidden
            this.Write(")\r\n                    ");
            
            #line 95 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        if (relationship.IsRequired)
        {

            
            #line default
            #line hidden
            this.Write(".IsRequired()");
            
            #line 98 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

        }

            
            #line default
            #line hidden
            this.Write("                    .OnDelete(DeleteBehavior.");
            
            #line 101 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.DeleteBehavior));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 102 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }

            
            #line default
            #line hidden
            
            #line 105 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    foreach (var relationship in EntityOptions.ManyToManyRelationships)
    {

            
            #line default
            #line hidden
            this.Write("            builder.HasMany(x => x.");
            
            #line 109 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.LeftEntity));
            
            #line default
            #line hidden
            this.Write(")\r\n                    .WithMany(x => x.");
            
            #line 110 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationship.RightEntity));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 111 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 119 "D:\Projects\constructor\src\Constructor.Core\Templates\EntityConfiguration.tt"

    public EntityOptions EntityOptions { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class EntityConfigurationBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
